global:
  resolve_timeout: 1m

route:
  receiver: "jenkins-rollback-webhook"
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: "jenkins-rollback-webhook"
    webhook_configs:
      - url: "http://13.206.54.52:8080/generic-webhook-trigger/invoke?token=ROLLBACK_6556B2_TOKEN"
        send_resolved: false
        http_config:
          basic_auth:
            username: "HASSAN123"
            password: "1190238958b6c6f7aa6e38d5acc27eca41"
